from kratos_agent.brain.config import (
    DEFAULT_BASE_URL,
    DEFAULT_CHAT_ENDPOINT,
    DEFAULT_MODEL_ENDPOINT,
    DEFAULT_MODEL,
    DEFAULT_TIMEOUT_SECONDS,
    DEFAULT_MAX_RETRIES,
    PUBLIC_MODELS,
    get_base_url,
    get_endpoint_url,
    get_model_endpoint_url,
    get_api_key,
    get_default_model,
    get_request_timeout,
    get_max_retries,
    authenticate,
    BrainError,
    BrainConnectionError,
    BrainTimeoutError,
    BrainRateLimitError,
    BrainBadRequestError,
    BrainNotFoundError,
    BrainServerError,
    # Backward compatibility aliases
    DEFAULT_OMNIROUTE_URL,
    OmnirouteError,
    OmnirouteConnectionError,
    OmnirouteTimeoutError,
    OmnirouteRateLimitError,
    OmnirouteBadRequestError,
    OmnirouteNotFoundError,
    OmnirouteServerError,
)
from kratos_agent.brain.config import get_model, fetch_models
from kratos_agent.brain.client import BrainClient, OmnirouteClient
from kratos_agent.brain.chat_model import (
    BrainChatModel,
    OmnirouteChatModel,
    extract_tool_calls_from_text,
    clean_file_path,
)
from kratos_agent.brain.brain import (
    get_agent_response,
    create_brain_llm,
    get_http_client,
)

__all__ = [
    "DEFAULT_BASE_URL",
    "DEFAULT_CHAT_ENDPOINT",
    "DEFAULT_MODEL_ENDPOINT",
    "DEFAULT_MODEL",
    "DEFAULT_TIMEOUT_SECONDS",
    "DEFAULT_MAX_RETRIES",
    "PUBLIC_MODELS",
    "get_base_url",
    "get_endpoint_url",
    "get_model_endpoint_url",
    "get_api_key",
    "get_default_model",
    "get_request_timeout",
    "get_max_retries",
    "authenticate",
    "get_model",
    "fetch_models",
    "BrainError",
    "BrainConnectionError",
    "BrainTimeoutError",
    "BrainRateLimitError",
    "BrainBadRequestError",
    "BrainNotFoundError",
    "BrainServerError",
    "BrainClient",
    "BrainChatModel",
    "extract_tool_calls_from_text",
    "clean_file_path",
    "get_agent_response",
    "create_brain_llm",
    "get_http_client",
    # Compatibility
    "DEFAULT_OMNIROUTE_URL",
    "OmnirouteError",
    "OmnirouteConnectionError",
    "OmnirouteTimeoutError",
    "OmnirouteRateLimitError",
    "OmnirouteBadRequestError",
    "OmnirouteNotFoundError",
    "OmnirouteServerError",
    "OmnirouteClient",
    "OmnirouteChatModel",
]
